# Site settings
title: YonBergman
email: contact@yonbergman.com
description: "Where we create pretty things and share them"
baseurl: ""
url: "http://www.yonbergman.com"
username: 'yonbergman'

# Build settings
markdown: redcarpet
permalink: pretty
